spring:
  security:
  datasource:
    url: jdbc:mysql://localhost:3306/tslcompany
    username: root
    password: admin
  liquibase:
    change-log: classpath:db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          ssl:
            enable: false


